# Generated by Django 6.0.5 on 2026-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_end",
            field=models.DateField(blank=True, null=True, verbose_name="계약 종료일"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_start",
            field=models.DateField(blank=True, null=True, verbose_name="계약 시작일"),
        ),
    ]
